MKLINK /D  "c:\Users\fademind\AppData\Local\EpicGamesLauncher" "d:\fademind\AppData\Local\EpicGamesLauncher"
MKLINK /D  "c:\Users\fademind\AppData\Local\GOG.com" "d:\fademind\AppData\Local\GOG.com"
MKLINK /D  "c:\Users\fademind\AppData\Local\Google" "d:\fademind\AppData\Local\Google"
MKLINK /D  "c:\Users\fademind\AppData\Local\Mega Limited" "d:\fademind\AppData\Local\Mega Limited"
MKLINK /D  "c:\Users\fademind\AppData\Local\Origin" "d:\fademind\AppData\Local\Origin"
MKLINK /D  "c:\Users\fademind\AppData\Local\Spotify" "d:\fademind\AppData\Local\Spotify"
MKLINK /D  "c:\Users\fademind\AppData\Local\Steam" "d:\fademind\AppData\Local\Steam"
MKLINK /D  "c:\Users\fademind\AppData\Local\Thunderbird" "d:\fademind\AppData\Local\Thunderbird"
MKLINK /D  "c:\Users\fademind\AppData\Local\Ubisoft Game Launcher" "d:\fademind\AppData\Local\Ubisoft Game Launcher"
MKLINK /D  "c:\Users\fademind\AppData\Local\cFos" "d:\fademind\AppData\Local\cFos"
MKLINK /D  "c:\Users\fademind\AppData\Local\converseen" "d:\fademind\AppData\Local\converseen"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\AIMP" "d:\fademind\AppData\Roaming\AIMP"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Acronis" "d:\fademind\AppData\Roaming\Acronis"
:: GitHub Desktop
MKLINK /D  "c:\Users\fademind\AppData\Roaming\GitHub Desktop" "d:\fademind\AppData\Roaming\GitHub Desktop"
:: Authy
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Authy Desktop" "d:\fademind\AppData\Roaming\Authy Desktop"
:: BatteryBar
MKLINK /D  "c:\Users\fademind\AppData\Roaming\BatteryBar" "d:\fademind\AppData\Roaming\BatteryBar"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Burnaware" "d:\fademind\AppData\Roaming\Burnaware"
:: IDM
MKLINK /D  "c:\Users\fademind\AppData\Roaming\IDM" "d:\fademind\AppData\Roaming\IDM"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\IrfanView" "d:\fademind\AppData\Roaming\IrfanView"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\KC Softwares" "d:\fademind\AppData\Roaming\KC Softwares"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Kodi" "d:\fademind\AppData\Roaming\Kodi"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Notepad++" "d:\fademind\AppData\Roaming\Notepad++"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Origin" "d:\fademind\AppData\Roaming\Origin"
:: Adguard cannot handle it :: MKLINK /D  "c:\Users\fademind\AppData\Roaming\Spotify" "d:\fademind\AppData\Roaming\Spotify"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Thunderbird" "d:\fademind\AppData\Roaming\Thunderbird"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\WinRAR" "d:\fademind\AppData\Roaming\WinRAR"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\copyq" "d:\fademind\AppData\Roaming\copyq"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\picpick" "d:\fademind\AppData\Roaming\picpick"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\qBittorrent" "d:\fademind\AppData\Roaming\qBittorrent"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\Bitwarden" "d:\fademind\AppData\Roaming\Bitwarden"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\discord" "d:\fademind\AppData\Roaming\discord"
MKLINK /D  "c:\Users\fademind\AppData\Roaming\vlc" "d:\fademind\AppData\Roaming\vlc"
MKLINK /D  "c:\Users\fademind\AppData\Local\Microsoft\Outlook" "d:\fademind\AppData\Local\Microsoft\Outlook"
rd /s /q "c:\Users\fademind\AppData\Local\Microsoft\Edge"
MKLINK /D  "c:\Users\fademind\AppData\Local\Microsoft\Edge" "d:\fademind\AppData\Local\Microsoft\Edge"
rd /s /q "c:\Users\fademind\AppData\Local\Microsoft\Windows\Themes"
MKLINK /D  "c:\Users\fademind\AppData\Local\Microsoft\Windows\Themes" "d:\fademind\AppData\Local\Microsoft\Windows\Themes"
MKLINK /D  "c:\Users\fademind\AppData\Local\Chomikbox" "d:\fademind\AppData\Local\Chomikbox"