takeown /f "D:\fademind" /r
icacls "D:\fademind" /reset /T
takeown /f "D:\WIFI" /r
icacls "D:\WIFI" /reset /T
takeown /f "D:\ACRNIS" /r
icacls "D:\ACRNIS" /reset /T
takeown /f "D:\SteamLibrary" /r
icacls "D:\SteamLibrary" /reset /T
takeown /f "D:\INSTALL_DIR" /r
icacls "D:\INSTALL_DIR" /reset /T
